# Generated by Django 5.0.1 on 2024-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(default=0, upload_to='filefolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
